[package]
name = "proxmox-systemd"
description = """
Utilities for dealing with systemd unit files and communicating with systemd.
"""
version = "1.0.0"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libc.workspace = true
