[package]
name = "proxmox-resource-scheduling"
version = "1.0.0"
description = "Proxmox library for resource scheduling"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = [ "derive" ] }
