[package]
name = "proxmox-login"
description = "proxmox product authentication api"
version = "0.2.0"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
percent-encoding.workspace = true
serde = { workspace = true, features = [ "derive" ] }
serde_json.workspace = true
proxmox-serde = { workspace = true, features = [ "perl" ] }

# For webauthn types
webauthn-rs = { workspace = true, optional = true }

# For `Authentication::set_auth_headers`
http = { workspace = true, optional = true }

[target.'cfg(target_arch="wasm32")'.dependencies]
js-sys = "0.3.55"

[features]
default = []
webauthn = [ "dep:webauthn-rs" ]
http = ["dep:http"]
