[package]
name = "proxmox-sys"
description = "System tools (using nix)."
version = "1.0.0"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
log.workspace = true
nix = { workspace = true, features = [ "dir", "fs", "ioctl", "mman", "net", "process", "signal", "socket", "user" ] }
openssl = { workspace = true, optional = true }
regex.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = [ "derive" ] }
zstd = { workspace = true, optional = true}

proxmox-io.workspace = true
proxmox-lang.workspace = true

[features]
default = []
logrotate = ["dep:zstd"]
acl = []
crypt = ["dep:openssl"]
timer = []
