[package]
name = "proxmox-serde"
description = "Serde formatting tools"
version = "0.1.2"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }

proxmox-base64 = { workspace = true, features = ["serde"] }
proxmox-time.workspace = true

[dev-dependencies]
serde_json.workspace = true

[features]
perl = []
