[package]
name = "proxmox-ldap"
description = "Proxmox library for LDAP authentication/synchronization"
version = "1.0.0"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
ldap3 = { workspace = true, default-features = false, features = ["tls"] }
serde = { workspace = true, features = ["derive"] }
native-tls.workspace = true

[dev-dependencies]
proxmox-async.workspace = true
