[package]
name = "proxmox-metrics"
description = "Metrics Server export utilitites"
version = "1.0.0"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
http.workspace = true
hyper.workspace = true
openssl.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = [ "net", "sync" ] }
form_urlencoded.workspace = true

proxmox-async.workspace = true
proxmox-http = { workspace = true, features = [ "client" ] }
