[package]
name = "proxmox-shared-cache"
description = "A cache that can be used from multiple processes simultaneously"
version = "1.0.0"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
nix.workspace = true
serde = { workspace = true, features = ["derive"]}
serde_json = { workspace = true, features = ["raw_value"] }

proxmox-sys = { workspace = true, features = ["timer"] }
